# Generated by Django 4.2.10 on 2024-03-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmonews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='code',
        ),
    ]
